- back-end/node-js/index.js
- back-end/node-js/src/controllers/DetalleController.js
- back-end/node-js/src/controllers/FichaController.js
- back-end/node-js/src/controllers/TipoFichaController.js
- back-end/node-js/src/controllers/VariableController.js
- back-end/node-js/src/database/database.js
- back-end/node-js/src/routes/DetalleRoutes.js
- back-end/node-js/src/routes/FichaRoutes.js
- back-end/node-js/src/routes/TipoFichaRoutes.js
- back-end/node-js/src/routes/VariableRoutes.js
se añadio cruds de las tablas TipoFicha, Ficha, detalles y variables de la base de datos.
> se añadio cruds de las tablas TipoFicha, Ficha, detalles y variables

- back-end/node-js/index.js
- back-end/node-js/package-lock.json
- back-end/node-js/src/controllers/areasController.js
- back-end/node-js/src/controllers/centrosController.js
- back-end/node-js/src/controllers/sedesController.js
- back-end/node-js/src/controllers/sitiosController.js
- back-end/node-js/src/controllers/tipo_sitioController.js
- back-end/node-js/src/database/database.js
- back-end/node-js/src/routes/areasRouter.js
- back-end/node-js/src/routes/centrosRouter.js
- back-end/node-js/src/routes/sedesRouter.js
- back-end/node-js/src/routes/sitiosRouter.js
- back-end/node-js/src/routes/tipo_sitioRouter.js
Añadí las apis de centros, sedes, areas, sitios y tipo_sitios
Ya hice algunas pruebas en insomnia con mi propia bd y todo salio bien. Tambien añadi las importaciones al index
Todo esta bien y funciona hasta donde yo vi con las pruebas que hice
En total añadí cinco controladores: centrosController.js, sedesController.js, areasController.js, sitiosController.js y tipo_sitioController.js
Cinco rutas: centrosRouter.js, sedesRouter.js, areasRouter.js, sitiosRouter.js y tipo_sitioRouter.js
En el index solo añadi las importaciones y asigne unas rutas
> Añadir apis

- back-end/node-js/public/estilos.css
- back-end/node-js/src/controllers/mantenimientoController.js
- back-end/node-js/src/routes/mantenimientoRuter.js
- back-end/node-js/views/documentacion.ejs
todos mis requerimientos funciónales 5, 14, 17 en base a el documento  2 v.1.1. EspecificaciónDeRequisitosDeSoftware  y la documentación del requerimiento 5
> requerimientos

- back-end/node-js/src/controllers/mantenimientoController.js
los cambios ya vistos antes solo que con algunas cosas corregidas
> cambios para ver errores

- back-end/node-js/public/estilos.css
- back-end/node-js/src/controllers/activitiesController.js
- back-end/node-js/views/documentacion.ejs
añado la documentacion de mis requerimientos, me tome la libertad y hice algunos cambios en mis cruds, muy censillos y hice un pequeño cambio en el css donde añadi un metodo mas el de 'delete'.
> añadiendo documentacion a los requerimientos 6, 6.1 y 6,2

- back-end/node-js/src/controllers/FichaController.js
- back-end/node-js/views/documentacion.ejs
Documentacion en la api de los requerimientos 11, 12, 13 y 15 junto con todos sus derivados.
> se añadio documentacion de los requerimientos 11, 12, 13 y 15

- back-end/node-js/views/documentacion.ejs
actualice el color de el requerimiento 5, 14 y 16, además de agregar los requerimientos 14 y 16 funcionales
> requerimiento 14 y 16

- back-end/node-js/public/estilos.css
- back-end/node-js/src/controllers/activitiesController.js
- back-end/node-js/views/documentacion.ejs
hice unos cambios menores en mi controllador en actulizar de la salidad de actualizar
> cambie la salida de datos en la documentacion

- back-end/node-js/src/controllers/mantenimientoController.js
- back-end/node-js/src/routes/mantenimientoRuter.js
e elimino las listas, y registros innecesarios y se quedaron solo listas y registros que son a base de los requerimientos
> cambios radicales en mi rama

- back-end/node-js/views/documentacion.ejs
cambie la documentación del requerimiento 16 de acuerdo a la nueva información
> cambios en la documentacion del requerimiento 16

- back-end/node-js/src/controllers/activitiesController.js
ahora cuando se liste una actividad aparecera el nombre y rol de quien hizo esa actividad
> añadiendo tecnicos al listar actividades

- back-end/node-js/src/controllers/mantenimientoController.js
- back-end/node-js/src/controllers/tipoMantController.js
- back-end/node-js/src/routes/mantenimientoRuter.js
- back-end/node-js/src/routes/tipoMantRoutes.js
- back-end/node-js/validar/mantenimiento/mantenimiento_validar.js
- back-end/node-js/validar/mantenimiento/tipo_mantenimiento_validar.js
se agrego validar datos ingresado y validar token
> validar datos y token

- back-end/node-js/src/config/mantenimiento_email/email_mantenimineto.js
- back-end/node-js/src/config/mantenimiento_email/emailhtml_mantenimiento.js
- back-end/node-js/src/controllers/mantenimientoController.js
- back-end/node-js/src/routes/mantenimientoRuter.js
- back-end/node-js/validar/mantenimiento/mantenimiento_validar.js
eliminar console.log() innecesarios
> corrección de 5.1 envió de correos 

- back-end/node-js/views/documentacion.ejs
agregue la documentación del requerimiento 5.1 Generar alertas de mantenimiento de a través de correo electrónico
> documentacion de 5.1

- front-end/machinapp/src/pages/Ambientes.jsx
- front-end/machinapp/src/pages/Areas.jsx
- front-end/machinapp/src/pages/Sedes.jsx
- front-end/machinapp/src/pages/Sitios.jsx
Se añadieron los cambios que habia hecho antes de deshacer los commits
En el App.jsx va lo siguiente:
const Sitios = lazy(() => import("./pages/Sitios"));
const Sedes = lazy(() => import("./pages/Sedes"));
const Areas = lazy(() => import("./pages/Areas"));
const Ambientes = lazy(() => import("./pages/Ambientes"));
<Route path="/Sitios" element={<Sitios/>}/>
<Route path="/Sedes" element={<Sedes/>}/>
<Route path="/Areas" element={<Areas/>}/>
<Route path="/Ambientes" element={<Ambientes/>}/>
> sedes, areas, ambientes y sitios

- front-end/machinapp/src/App.jsx
- front-end/machinapp/src/components/organisms/ListarAmbientes.jsx
- front-end/machinapp/src/components/organisms/ListarAreas.jsx
- front-end/machinapp/src/components/organisms/ListarSedes.jsx
- front-end/machinapp/src/pages/Areas.jsx
- front-end/machinapp/src/pages/Sedes.jsx
- front-end/machinapp/src/pages/Sitios.jsx
Se añadio la opcion de listar por lugar. Ejemplo: Listar areas por sede o listar ambientes por area, ya que antes listaba todo sin excepcion.
> cambios importantes radicales en mi frontend

- front-end/machinapp/package-lock.json
- front-end/machinapp/package.json
- front-end/machinapp/src/components/molecules/Calendario.jsx
- front-end/machinapp/src/components/organisms/ListarActividades.jsx
- front-end/machinapp/src/components/organisms/Paginacentrar.jsx
> Subiendo el calendario

- back-end/node-js/src/controllers/mantenimientoController.js
- back-end/node-js/src/controllers/partes_mantenimiento_controller.js
- back-end/node-js/src/routes/partesMantRoutes.js
- front-end/machinapp/src/components/organisms/MantenimientoGeneral.jsx
- front-end/machinapp/src/components/organisms/formularios/FormFichaDeMante.jsx
- front-end/machinapp/src/pages/Fichas.jsx
- front-end/machinapp/src/pages/Historial.jsx
- front-end/machinapp/src/pages/fichastecnicas/ViewFormFicha_de_mantenimiento.jsx
back end
agregue mi back end modificado a la nueva base de datos,
agregue en controlador partes de mantenimiento,
agreguar a index
import partesMantRoutes from "./src/routes/partesMantRoutes.js",
serve.use('/partes_mantenimiento',partesMantRoutes)
front end
en Router.jsx agreguar:
import { ViewFormFicha_De_mantenimiento} from "../pages/fichastecnicas/ViewFormFicha_de_mantenimiento"
<Route path="/crear_ficha_mantenimiento" element={<ViewFormFicha_De_mantenimiento />}/>
agregue la ficha de mantenimiento,
agreguar historial,
en /pages/fichastecnicas agrege ViewFormFicha_de_mantenimiento,
en components/organisms/formularios agrege FormFichaDeMante,
modifique el mantenimiento
> historial y mantenimiento

- back-end/node-js/src/controllers/mantenimientoController.js
- front-end/machinapp/src/components/molecules/Nav.jsx
- front-end/machinapp/src/pages/Fichas.jsx
- front-end/machinapp/src/pages/Maquinas.jsx
- front-end/machinapp/src/pages/fichastecnicas/ViewFormFichaEquipos.jsx
- front-end/machinapp/src/pages/fichastecnicas/ViewFormFicha_de_mantenimiento.jsx
cambie fichas por solicitud, maquinas por equipos, agrege
titlePage={"Ficha tecnica"}> y titlePage={"Ficha de mantenimiento"}> a sus respectivos formularios.
agrege Fichas de Maquinas a equipos.
> Cambios leves a el front end relacionados con fichas y maquinas

- front-end/machinapp/src/components/organisms/Sitios/ListarAmbientes.jsx
- front-end/machinapp/src/components/organisms/Sitios/ListarAmbientesGeneral.jsx
- front-end/machinapp/src/components/organisms/Sitios/ListarAreas.jsx
- front-end/machinapp/src/components/organisms/Sitios/ListarAreasGeneral.jsx
- front-end/machinapp/src/components/organisms/Sitios/ListarSedes.jsx
- front-end/machinapp/src/components/organisms/formularios/FormAmbientesUpdate.jsx
- front-end/machinapp/src/components/organisms/formularios/FormAreasUpdate.jsx
- front-end/machinapp/src/components/organisms/formularios/FormSedesUpdate.jsx
- front-end/machinapp/src/pages/Sitios/ActualizarAmbiente.jsx
- front-end/machinapp/src/pages/Sitios/ActualizarArea.jsx
- front-end/machinapp/src/pages/Sitios/ActualizarSede.jsx
Se añadio la opcion de actualizar sedes, areas y ambientes
Cosas a añadir en src/pages/index.js:
export { ActualizarAmbiente } from "./Sitios/ActualizarAmbiente";
export { ActualizarArea } from "./Sitios/ActualizarArea";
export { ActualizarSede } from "./Sitios/ActualizarSede"; 
Cosas a añadir en router.jsx:
En la parte de las importaciones:
ActualizarAmbiente,
ActualizarArea,
ActualizarSede
En la parte de las rutas:
<Route path="/Ambientes/Actualizar/:id" element={<ActualizarAmbiente />} />
<Route path="/Areas/Actualizar/:id" element={<ActualizarArea />} />
<Route path="/Sedes/Actualizar/:id" element={<ActualizarSede />} />
> añadir actualizar sitios
